name: Deploy HTML to Azure Web App - student-registration-yourname

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C48CA1EA1A4F5D9E3C7ED8C26137B4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_13745DB295BE40E0A4E2E264087A3971 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_044E3DD8391C43C49AD9AF0B6A4F73D7 }}

      - name: Deploy HTML to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'student-registration-yourname'
          slot-name: 'Production'
          package: .
